favicon: false
color-scheme: auto

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - getting-started
  - label: Bill of Materials
    children:
      - bom
      - custom-pcbs
      - bom/custom-cables
      - custom-3d
  - label: Building the Robot
    children:
      - assembly-intro
      - part-fabrication
      - assembly-control
      - assembly-motors
      - assembly-lower-body
      - assembly-torso
      - assembly-arms
      - assembly-final
  - label: Testing the Robot
    children:
      - software-setup
  - sami-sim
  - label: Software Documentation
    children:
      - software-architecture
      - behavior-guide
      - comm-protocol
  - label: Hardware Documentation
    children:
      - angle-ranges
      - hardware-modification
  - label: Miscellaneous
  - label: Example Applications
